---
- name: Setup and configure app_servers
  hosts: app_servers
  become: yes

  roles:
    - role: firewall
      vars:
        firewall_tcp_ports:
          - 8080
    - role: flask
      vars:
        flask_app_name: resource_hub
        flask_repo: https://github.com/tonykay/resource_hub.git
