---
- name: Setup and configure load_balancers
  hosts: load_balancers
  become: yes

  roles:
    - role: firewall
      vars:
        firewall_services:
          - http
    - role: haproxy
      vars:
        haproxy_backend_servers:
          - name: app1
            address: app1.example.com:8080
          - name: app2
            address: app2.example.com:8080
