---
- name: Handle bind9-pod zone file
  hosts: control
  become: true
  gather_facts: false

  handlers:
    - name: restart bind9-pod
      ansible.builtin.systemd:
        name: '{{ bind9_pod_service }}'
        state: restarted

  tasks:
    - name: Include vars for control_node
      ansible.builtin.include_vars: group_vars/control_node.yml

    - name: Openstack instances
      ansible.builtin.os_server_info:
        cloud: '{{ GUID }}-project'
      delegate_to: localhost
      connection: local
      register: osp_instances
      become: false

    - name: Create bind9-pod zone file
      ansible.builtin.template:
        src: templates/{{ domain }}.zone.j2
        dest: '{{ bind9_pod_zone_file }}'
        owner: root
        group: root
        mode: 0644
      notify: restart bind9-pod
