---
- name: Handle bind9-pod zone file
  hosts: control
  become: true
  gather_facts: false
  vars:
    bind9_pod_service: bind9-pod.service
    bind9_pod_zone_file: /opt/podman/volumes/bind9-volume/var/named/{{ domain }}.zone

  handlers:
    - name: restart bind9-pod
      ansible.builtin.systemd:
        name: '{{ bind9_pod_service }}'
        state: restarted

  tasks:
    - name: Openstack instances
      ansible.builtin.os_server_info:
        region_name: "{{ openstack_region | default('regionOne') }}"
      delegate_to: localhost
      connection: local
      register: osp_instances
      become: false

    - name: Create bind9-pod zone file
      ansible.builtin.template:
        src: templates/{{ domain }}.zone.j2
        dest: '{{ bind9_pod_zone_file }}'
        owner: root
        group: root
        mode: 0644
      notify: restart bind9-pod
