---
- name: PostgreSQL and End-to-end smoke tests
  hosts: app_servers:database_servers
  gather_facts: false
  become: yes

  tasks:
    - name: PostgreSQL ping database
      postgresql_ping:
        db: flask_db
        login_host: '{{ groups.database_servers[0] }}'
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: '{{ groups.app_servers[0] }}'
      run_once: true

- name: End to end smoke tests
  hosts: app_servers
  become: no
  gather_facts: false

  tasks:
    - name: Check webserver for correct response
      uri:
        url: 'http://frontend1.{{ domain }}/ping'
        return_content: yes
      until: '"alive" in result.content'
      retries: 10
      delay: 1
      register: result
      delegate_to: localhost
      connection: local
