---
- name: Building inventory
  hosts: control_node
  vars:
    meta_ansiblegroup:
      - load_balancers
      - app_servers
      - database_servers

  tasks:
    - name: Fetch Instance Info
      ansible.builtin.os_server_info:
        region_name: "{{ openstack_region | default('regionOne') }}"
      register: r_instances

    - name: Add host(s) to inventory
      when: '__instance.metadata.AnsibleGroup in meta_ansiblegroup'
      ansible.builtin.add_host:
        name: '{{ __instance.private_v4 }}'
        group:
          - '{{ __instance.metadata.AnsibleGroup }}'
      loop: '{{ r_instances.openstack_servers }}'
      loop_control:
        loop_var: __instance
        label: '{{ __instance.private_v4 }} [{{ __instance.name }}]'

- name: Test connectivity
  hosts: load_balancers,app_servers,database_servers
  gather_facts: false
  tasks:
    - name: Ping OSP instance
      ansible.builtin.ping:
