---
# tasks file for roles/flask

- name: Install Flask packages
  ansible.builtin.package:
    name: '{{ __package }}'
    state: present
  loop:
    - '{{ flask_packages }}'
  loop_control:
    loop_var: __package

- name: Create Flask user
  ansible.builtin.user:
    name: '{{ flask_user }}'
    state: present

- name: Setup Flask repo
  block:
    - name: Clone Flask repo
      ansible.builtin.git:
        repo: '{{ flask_repo }}'
        dest: '{{ flask_home }}/{{ flask_app_name }}'
        update: yes
        force: yes

    - name: Change Flask repo owner recursively
      ansible.builtin.file:
        dest: '{{ flask_home }}/{{ flask_app_name }}'
        owner: '{{ flask_user }}'

- name: Virtualenv setup
  block:
    - name: Setup pre-requisite pip3 packages inside venv
      ansible.builtin.pip:
        name: '{{ pip_dependencies }}'
        state: latest
        virtualenv: '{{ virtualenv_home }}/{{ flask_app_name }}'
        virtualenv_site_packages: no

    - name: 'Create virtualenv {{ virtualenv_name }} for Flask'
      ansible.builtin.pip:
        requirements: '{{ flask_home }}/{{ flask_app_name }}/requirements.txt'
        virtualenv: '{{ virtualenv_home }}/{{ flask_app_name }}'
        virtualenv_site_packages: no

- name: Initialize Flask app database resources
  ansible.builtin.command:
    argv:
      - '{{ virtualenv_home }}/{{ flask_app_name }}/bin/python3'
      - '{{ flask_home }}/{{ flask_app_name }}/config.py'
  run_once: true

- name: systemd unit file
  block:
    - name: 'Copy {{ flask_app_name }} launch script in place'
      ansible.builtin.template:
        src: launch_{{ flask_app_name }}.j2
        dest: '{{ flask_app_lauch_path }}/launch_{{ flask_app_name }}'
        mode: 0555

    - name: 'Copy {{ flask_app_name }} systemd unit file in place'
      ansible.builtin.template:
        src: flask_service.j2
        dest: /etc/systemd/system/{{ flask_app_name }}.service
        mode: 0755

    - name: 'Ensure {{ flask_app_name }} is started and enabled on boot'
      ansible.builtin.systemd:
        daemon_reload: yes
        name: '{{ flask_app_name }}'
        enabled: yes
        state: started
