---
# vars file for roles/postgresql RedHat-8

postgresql_repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
postgresql_version: '12'
postgresql_packages:
  - postgresql{{ postgresql_version }}
  - postgresql{{ postgresql_version }}-server
  - postgresql{{ postgresql_version }}-contrib
  - postgresql{{ postgresql_version }}-libs
postgresql_python_library: python3-psycopg2
postgresql_service: postgresql-{{ postgresql_version }}.service
postgresql_config_path: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_data_path: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_bin_path: /usr/pgsql-{{ postgresql_version }}/bin
postgresql_setup_cmd: '{{ postgresql_bin_path }}/postgresql-{{ postgresql_version }}-setup'
