---
- name: Install firewall packages
  ansible.builtin.package:
    name: '{{ __package }}'
    state: latest
  loop: '{{ firewall_packages }}'
  loop_control:
    loop_var: __package

- name: Ensure firewall is started and enabled on boot
  ansible.builtin.systemd:
    name: '{{ firewall_service_name }}'
    enabled: yes
    state: started

- name: Open service port
  when: firewall_services is defined
  ansible.builtin.firewalld:
    service: '{{ __service }}'
    immediate: yes
    permanent: yes
    state: enabled
  loop: '{{ firewall_services }}'
  loop_control:
    loop_var: __service

- name: Open tcp port
  when: firewall_tcp_ports is defined
  ansible.builtin.firewalld:
    port: '{{ __tcp_port }}/tcp'
    immediate: yes
    permanent: yes
    state: enabled
  loop: '{{ firewall_tcp_ports }}'
  loop_control:
    loop_var: __tcp_port

- name: Open tcp port
  when: firewall_udp_ports is defined
  ansible.builtin.firewalld:
    port: '{{ __udp_port }}/udp'
    immediate: yes
    permanent: yes
    state: enabled
  loop: '{{ firewall_udp_ports }}'
  loop_control:
    loop_var: __udp_port
