---
# defaults file for roles/postgresql

postgresql_port: 5432
postgresql_user: postgres
postgresql_group: postgres

postgresql_users: []
postgresql_databases: []

postgresql_hba_entries:
  - {type: local, database: all, user: all, auth_method: ident}
  - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5}
  - {type: host, database: all, user: all, address: '::0/0', auth_method: md5}
  - {type: host, database: all, user: all, address: 'all', auth_method: md5}

postgresql_gpg_key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
